---
version: '3'
services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: docker-script/prod/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Seoul
    #command: sh -c "./wait-for-it.sh 127.0.0.1:8080 -- nginx -g 'daemon off;'"
    volumes:
      - /var/log/nginx:/var/log/nginx # volume
    stdin_open: true
    tty: true
    depends_on:
      - mysql
      - shopping-mall

  mysql:
    build:
      dockerfile: Dockerfile
      context: docker-script/prod/db/mysql
    container_name: mysql
    restart: always
    ports:
      - "3206:3306" # host port : container port
    volumes:
      #- ./docker-script/db/mysql/init:/docker-entrypoint-initdb.d
      - ./docker-script/db/mysql/conf.d:/etc/mysql/conf.d
      #- ./docker-script/db/mysql/data:/var/lib/mysql
      - mydata:/var/lib/mysql
    env_file:
      - ./docker-script/prod/db/mysql/.env
    environment:
      - TZ=Asia/Seoul
    command: [ # TODO: my.cnf 설정 안먹는 것 같음, 확인 및 수정 필요 :  # https://gist.github.com/feltnerm/bb6e23f531803896ca1e
      'mysqld',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      "--lower_case_table_names=1" # 0: 테이블 생성시 대소문자 구분, 1: 대소문자 상관없이 소문자로 인식하여 생성, 2: 윈도우에서 대소문자 구분하여 테이블 가져옴
    ]

  shopping-mall:
    build:
      dockerfile: Dockerfile.prod
      context: app/shop
    container_name: shopping-mall
    restart: always # no: no restart | always: exit code와 상관없이 항상 재시작 | on-failure : exit code 0 아닐때만 재시작 | unless-stopped: 수동 stop 전까지 재시작
    ports:
      - "8082:8082"
    env_file:
      - ./app/shop/.env-prod
    environment:
      - TZ=Asia/Seoul
    volumes:
      - appdata:/data/app_logs
    depends_on:
      - mysql
      - nginx

volumes:
  mydata:
  appdata:

# bridge(default) - 호스트 pc와 별도의 가상 네트워크 사용 + port forwarding으로 외부 네트워크 연결
# host - container network 환경 호스트의 network 환경과 동일하게 구성
# none - networkd 사용 x + host, 외부 연결 단절
#networks:
#  shop-network: